[package]
name = "generic-max-function"
version = "0.1.0"
authors = ["ChenYikunReal <50993163+ChenYikunReal@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
